version: '2.1'
services:
  config_server:
    build:
      dockerfile: ./src/configServer/Dockerfile
      context: .
    container_name: configServerContainer
  
  discovery_server:
    build:
      dockerfile: ./src/discoveryServer/Dockerfile
      context: .
    container_name: discoveryServerContainer
    ports:
      - "9090:9090"
    depends_on:
      - "config_server"

  gateway:
    build:
      dockerfile: ./src/gateway/Dockerfile
      context: .
    container_name: gatewayContainer
    ports:
      - "8765:8765"
    depends_on:
      - "config_server"
      - "discovery_server"

  api:
    build:
      dockerfile: ./src/api/Dockerfile
      context: .
    container_name: apiContainer
    depends_on:
      - "config_server"
      - "discovery_server"
      - "gateway"