version: '2.1'
services:
  config_server:
    build:
      dockerfile: ./src/configServer/Dockerfile
      context: .
    container_name: configServerContainer
    ports:
      - "8888:8888"
  
  discovery_server:
    build:
      dockerfile: ./src/discoveryServer/Dockerfile
      context: .
    container_name: discoveryServerContainer
    ports:
      - "9090:9090"